inputs:
  network:
    description: "Deployment target (e.g ic)"
    default: "ic"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: yarn && yarn ws install

    - name: CREATE-IC-APP-REACT Demo | install & deploy
      shell: bash
      working-directory: examples/create-ic-app-react-demo
      run: |
        node scripts/prepare-build.js

        dfx start --clean --background
        dfx deploy counter --no-wallet
        dfx stop

        dfx identity use action
        dfx deploy --network ${{ inputs.network }} --no-wallet
