inputs:
  network:
    description: "Deployment target (e.g ic)"
    default: "ic"
  dfxVersion:
    description: "DFX version"
    default: "0.9.3"
runs:
  using: "composite"
  steps:
    - name: Setup mono repo
      shell: bash
      run: yarn

    - name: Install dependencies
      working-directory: examples/create-ic-app-react-demo
      shell: bash
      run: yarn

    - uses: aviate-labs/setup-dfx@v0.2.3
      with:
        dfx-version: ${{ inputs.dfxVersion }}

    - name: CREATE-IC-APP-REACT Demo | install & deploy
      shell: bash
      working-directory: examples/create-ic-app-react-demo
      run: |

        dfx start --background
        dfx deploy counter --no-wallet
        dfx stop

        dfx identity use action
        dfx deploy --network ${{ inputs.network }} --no-wallet
