blank_issues_enabled: false
contact_links:
  - name: NFID Community Support
    url: https://github.com/internet-identity-labs/NFID-SDK/discussions/categories/q-a
    about: Please ask and answer questions here.
