inputs:
  namespace:
    description: "Package namespace"
    default: "@internet-identity-labs"
  packageBasePath:
    description: "Package base path"
    default: "packages/"

  package:
    description: "Path to Package"
  registry:
    description: "NPM registry"
    default: "https://registry.npmjs.org"
  upgradeType:
    description: "Upgrade type (patch | minor | major)"
    default: "patch"
  accessType:
    description: "NPM access type"
    default: "public"
  gitUserName:
    description: "Git user name used for tags"
    default: "iil-github-bot"
  gitUserEmail:
    description: "Git user email used for tags"
    default: "iil-github-bot@indentitylabs.ooo"
runs:
  using: "composite"
  steps:
    - name: Install and test
      shell: bash
      working-directory: ${{inputs.packageBasePath}}${{ inputs.package }}
      run: yarn

    - name: Git configuration
      shell: bash
      run: |
        git config user.email "${{ inputs.gitUserEmail }}"
        git config user.name "${{ inputs.gitUserName }}"

    - name: Configure Yarn
      shell: bash
      run: |
        yarn config set version-git-message "ci(${{ inputs.package }}) Increment npm package version v%s"
        yarn config set version-tag-prefix "${{ inputs.namespace }}/${{ inputs.package }}"

    - name: Create new version
      shell: bash
      run: yarn version --${{ inputs.upgradeType }}

    - name: Update tags
      shell: bash
      run: |
        git push
        git push --tags

    - name: Publish package on NPM 📦
      shell: bash
      run: npm publish --access ${{ inputs.registry }}
