name: Dispatch NPM release

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: "Package to release"
        required: true
        options:
          - packages/nfid-sdk-react
          - packages/nfid-ui-kit-core
          - packages/react-ic-ii-auth
      level:
        type: choice
        description: Select the release update level
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM RELEASE
        uses: ./.github/actions/release-npm-package
        with:
          package: ${{ github.event.inputs.package }}
          upgradeType: ${{ github.event.inputs.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
