name: Dispatch NPM release

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: "Package to release"
        required: true
        options:
          - nfid-sdk-react
          - nfid-ui-kit-core
          - react-ic-ii-auth
      level:
        type: choice
        description: Select the release update level
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      - name: NPM RELEASE
        uses: ./.github/actions/release-npm-package
        with:
          package: ${{ github.event.inputs.package }}
          upgradeType: ${{ github.event.inputs.level }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
