name: NPM react-ic-ii-auth
on: workflow_dispatch

jobs:
  steps:
    - uses: actions/checkout@v2
    - name: NPM RELEASE
      uses: ./.github/actions/release-npm-package
      with:
        package: packages/react-ic-ii-auth
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
