name: CD DEV CREATE-IC-APP-REACT Demo
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mono repo
        shell: bash
        run: yarn

      - name: Install dependencies
        working-directory: examples/create-ic-app-react-demo
        shell: bash
        run: yarn

      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.9.3
        env:
          DFX_IDENTITY_PEM: ${{ secrets.PROD_GH_ACTION_DFX_IDENTITY_PEM }}

      - name: Deploy Demo (DEV)
        shell: bash
        env:
          DFX_IDENTITY_PEM: ${{ secrets.PROD_GH_ACTION_DFX_IDENTITY_PEM }}
          REACT_APP_NFID_PROVIDER_URL: https://nfid.dev/authenticate/?applicationName=NFID-Demo
        working-directory: examples/create-ic-app-react-demo
        run: |
          dfx identity use action
          dfx deploy --network dev demo_frontend --no-wallet
          dfx deploy --network dev demo_frontend_single_account --no-wallet
