name: CI/CD DEV
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NFID SDK
        run: |
          yarn
          yarn ws test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.9.2
        env:
          DFX_IDENTITY_PEM: ${{ secrets.GH_MP_ADMIN_PEM }}

      - name: CREATE-IC-APP-REACT Demo | install & deploy
        run: |
          cd examples/create-ic-app-react-demo && yarn

          dfx start --clean --background
          dfx deploy --no-wallet
          dfx stop

          dfx identity use action
          dfx deploy --network dev --no-wallet

        env:
          DFX_NETWORK: dev
          VITE_NFID_PROVIDER_URL: https://${{secrets.DEV_CANISTER_ID_NFID_FRONTEND}}.ic0.app/authenticate/?applicationName=NFID-Demo
          VITE_NFID_PROVIDER_IFRAME_URL: https://${{secrets.DEV_CANISTER_ID_NFID_FRONTEND}}.ic0.app/iframe-authenticate/?applicationName=NFID-Demo
