name: CD DEV CREATE-IC-APP-REACT Demo
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CREATE IC APP REACT DEMO | DEPLOY
        uses: ./.github/actions/create-ic-app-react-demo
        with:
          network: dev
        env:
          DFX_IDENTITY_PEM: ${{ secrets.PROD_GH_ACTION_DFX_IDENTITY_PEM }}
          FILTER_DEV_CANISTER: true
          DFX_NETWORK: dev
          REACT_APP_NFID_PROVIDER_URL: https://nfid.dev/authenticate/?applicationName=NFID-Demo
