name: CD DEV CREATE-IC-APP-REACT Demo
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.9.3
        env:
          DFX_IDENTITY_PEM: ${{ secrets.PROD_GH_ACTION_DFX_IDENTITY_PEM }}

      - name: Install dependencies
        run: yarn && yarn ws install

      - name: Deploy
        working-directory: examples/create-ic-app-react-demo
        run: |
          dfx start --clean --background
          dfx deploy counter --no-wallet
          dfx stop

          dfx identity use action
          dfx deploy --network dev --no-wallet

        env:
          DFX_NETWORK: dev
          REACT_APP_NFID_PROVIDER_URL: https://${{secrets.DEV_CANISTER_ID_NFID_FRONTEND}}.ic0.app/authenticate/?applicationName=NFID-Demo
          REACT_APP_NFID_PROVIDER_IFRAME_URL: https://${{secrets.DEV_CANISTER_ID_NFID_FRONTEND}}.ic0.app/iframe-authenticate/?applicationName=NFID-Demo
